replicaCount: 1

image:
  repository: devopsinfra56/gist-api
  pullPolicy: Always
  tag: "20260602-1937"

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
